### ISSUE TITLE
Many "Old Account" call notifications

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1163]
## Steps to reproduce
1. Have a Nextcloud instance and the Talk app
2. Reinstall Nextcloud instance from previous backup (part of message history is lost, could be relevant or not)
3. Log out from Nextcloud account in Talk app
4. Reinstall Talk app
5. Log back in

### Expected behaviour
If I receive a message or a notification for a call from the currently logged in account, which corresponds to the one which I was logged into before relogging and reinstalling the app, I would expect to receive the correct notifications.

### Actual behaviour
When I receive a call notification, it is correct but alongside it one or two notifications for "Call from Old Account" are spawned. This is annoying and unexpected, as the "Old Account" is the same account I am logged into now and is the same I was logged into previously.

## Device information

**Device:** iPhone X

**iOS version:** 16.3.1

**Talk version:** 16.0.0

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 26.0.0

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 16.0.0

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
> This is annoying and unexpected, as the "Old Account" is the same account I am logged into now and is the same I was logged into previously.

There's really nothing we can do about this from the talk-ios side. As soon as we receive a call notification, we are forced (by Apple) to show a call screen or otherwise the app gets killed by the OS.
I think the Problem is, that you logged out on the app after the instance was restored, because then we can't unsubscribe from the instance. So there's still a token on the new instance from the previous talk-ios installation. Since nothing else changed, this device still gets call notifications, which can't be decrypted, because the account on the app was deleted. But you also receive a correct notification, because you logged in again afterwards.

So you can only do what the app suggest in the settings and revoke the old tokens :)

**Comment by e-caste** [comment]
@SystemKeeper thank you for the detailed explanation, and sorry, I should have read the warning more carefully but when it happened I was outside. I'll close this issue!
  
For anyone wondering:
<img src=https://user-images.githubusercontent.com/48513706/227707039-977c9329-a611-4928-923b-3c0eb5f07f74.png width=250 />

**Comment by SystemKeeper** [comment]
I agree that this is annoying, but before we introduced that "Old calls" screen and briefly showing the call UI, the app just crashed because we did not correctly handle a call notification. So it's the best solution we can have right now..
