### ISSUE TITLE
The old user avatar is shown in the chat

### ISSUE THREAD

**Issue by e-caste** [nextcloud/spreed-ios#1227]
Perhaps related to https://github.com/nextcloud/talk-ios/issues/1226.

## Steps to reproduce
1. This bug happened to me (now fixed, at least for me): https://github.com/nextcloud/server/issues/34755
2. Regenerate the avatar cache on the server, wait a decent amount of time (now a few weeks have passed)

### Expected behaviour
The letter avatars in Talk iOS are synced to the updated version on the server.

### Actual behaviour
The letter avatars in Talk iOS:
- in notifications, are shown in light mode (probably expected since my phone is in dark mode for better contrast? I'm not sure)
- in the top bar, are shown in dark mode
- in the chat and the user's own profile, are not updated (see screenshot below, in the chat the avatar is not updated but it is correctly updated in the top bar)
![IMG_0253](https://user-images.githubusercontent.com/48513706/236838480-540eb04c-6917-48f6-b73d-e511cb086cd2.jpeg)

## Device information

**Device:** iPhone X

**iOS version:** 16.4.1 (a)

**Talk version:** 16.0.2

## Server information

**Nextcloud version:** (see admin overview page: `/index.php/settings/admin/overview`) 25.0.1

**Talk version:** (see apps admin page: `/index.php/settings/apps`) 16.0.3

**Custom Signaling server configured:** yes/no and version (see talk admin settings: `/index.php/settings/admin/talk#signaling_server`) no

**Custom TURN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#turn_server`) yes

**Custom STUN server configured:** yes/no (see talk admin settings: `/index.php/settings/admin/talk#stun_server`) yes

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by SystemKeeper** [comment]
> 2\. now a few weeks have passed

So after a few weeks you still see that empty avatar? That shouldn't be the case indeed. The avatar endpoint is quite heavily cached, but should request a new image latest after 24h. What you can try is to empty the image cache under settings and then restart the app. That should remove any caching. If it's not working after that, there still might be an issue. But since we changed the avatar handling completely in the latest version (see below), there won't be any updates to the 16 versions anymore.

#1226 only affects the latest TestFlight versions since we moved to a new library for images there.

**Comment by SystemKeeper** [comment]
Ah and regarding the light avatars... Apple only allows us to submit one avatar which is used in all themes... So currently we only submit light avatars, because it might be weird when people use that automatic light/dark mode switching... But I can see that it's irritating when permanently on dark mode. Maybe we could figure out if it's automatic or permanent and then go either way, not sure.

**Comment by e-caste** [comment]
@SystemKeeper yes even after a few weeks. I have tried what you've suggested (weirdly(?) the image cache goes from X MB to 0.7 MB, not 0), but it doesn't solve the issue. When I reopen the app I can see the blank avatars for a couple seconds before they get loaded, but in the chat the old version is still used.

**Comment by SystemKeeper** [comment]
Is it possible you could create a totally new user (like test12345) and then start a conversation with that new user? If that still doesn't work, we can rule out any caching on our side. Otherwise you could try to use the latest TestFlight which changes quite some things for avatars (but you probably should wait for Beta 2, because of #1223)

**Comment by e-caste** [comment]
Wouldn't that new user not have the old picture at all? What is shown in the screenshot is the old picture for sure, so if I create a new user without the server-side bug, it will only have the correct picture from the get-go

**Comment by SystemKeeper** [comment]
> Wouldn't that new user not have the old picture at all? 

No, I was talking about the new user. So when you add `test12345` start a conversation with that user and check if the avatar of `test12345` is shown. So we are sure that all avatars are correctly generated (because they did not exist before creating that user). Not the other way around.

**Comment by e-caste** [comment]
Okay, two updates about this:
1. New users have the correct image as expected (I don't remember when I have created test2 but test12345 is fresh)
![image](https://github.com/nextcloud/talk-ios/assets/48513706/866de89d-5408-4d95-ba88-67781ed2b470)
2. I tapped the name of my test user by mistake: this prompted the app to update the avatar in the top left corner for my view (when I'm logged in as test) but did not solve the issue in the chat thumbnails
![image](https://github.com/nextcloud/talk-ios/assets/48513706/c0096708-c14f-413c-9990-9d4b4942ede4)

**Comment by e-caste** [comment]
This has been fixed by updating Talk iOS to 17.0.0 and Nextcloud server to 27.0.0. I don't know which of the two was responsible.
![image](https://github.com/nextcloud/talk-ios/assets/48513706/2f931e56-cb80-429c-9065-3cddb486855c)

**Comment by SystemKeeper** [comment]
Thanks for confirming!
