### ISSUE TITLE
Open .md and office (docx, xlsx, ...) files for edit

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed-ios#676]
Currently I can open both file types read only
An option "open in files app for edit" would be nice.
see also: https://github.com/nextcloud/talk-android/issues/1683

**Comment by Ivansss** [comment]
"Open in Nextcloud" option should appear when you long press on top of a file message.

![IMG_E0109](https://user-images.githubusercontent.com/4638605/143604307-e96764e9-b335-49cd-80b3-3911a496b3ad.JPG)

**Comment by jakobroehrl** [comment]
Ohh, missed this option. 
Maybe it could helpful to show this "open in Nextcloud" in the read only preview mode auf a file. 
I think the workflow is to open the file and then maybe edit it.

**Comment by SystemKeeper** [comment]
> Maybe it could helpful to show this "open in Nextcloud" in the read only preview mode auf a file.

That might not be (easily) possible. The preview-view is a native iOS view which doesn't allow customization. I vaguely remember that there are limitations when you want to use it in another view or customize the navigation bar... That's why it is used as-is. Would need some research. If this really needs more attention, we could show a one time message box, when opening any file for the first time for this account... not too convinced of this, though.
