### ISSUE TITLE
can`t enable microphone after upgrade on 13.1.0 

### ISSUE THREAD

**Issue by ghost** [nextcloud/spreed-ios#720]
## Steps to reproduce
1. Upgrade on 13.1.0
2. Start a Call
3. Can`t enable microphone 

### Expected behaviour
the interlocutor should hear me

### Actual behaviour
the interlocutor sees that my microphone is turned off, but I can't turn it on (access to the microphone is activated in the application settings)

## Device information

**Device:** iPhone 12/13 12mini

**iOS version:** 15.3

**Talk version:** 13.1.0

## Server information

**Nextcloud version:** 22.2.3

**Talk version:** 12.2.3

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

**Comment by SystemKeeper** [comment]
Hello @md0raid1 

thanks for your report! This sounds like you don't have permission to use the microphone. Version 13.1.0 respects the detailed publishing permissions (Added in this PR: https://github.com/nextcloud/talk-ios/pull/713) introduced in Talk 13 and the behaviour can be seen, when a participant does not have the right permission:
![image](https://user-images.githubusercontent.com/1580193/152399344-66ac986d-b9a2-442f-97aa-d4f4e5e96f45.png)

But as you still use Talk 12, I'm not totally sure what the problem is. I noticed that the capability `publishing-permissions` was already introduced back in Talk 12 according to the docs (https://nextcloud-talk.readthedocs.io/en/latest/capabilities/), which might explain why the permission check fails. What client is the other person you're talking to using? Talk-ios as well or maybe the web version?

**Comment by ghost** [comment]
Hello, thank you for your reply. The interlocutors use different clients, including the Web version and clients on iOS and Android. The interlocutors on iOS who use the Talk version 13.0.0 do
not have any problems with them. The problem with microphone activation appeared only on iOS client 13.1.0, regardless of the interlocutor's client
![image](https://user-images.githubusercontent.com/98377951/152490304-a70bd481-9c52-4300-b248-88bfba1b60dd.png)

**Comment by stknet** [comment]
Same here on iOS. can't enable mircophone and camera. Permission is given for both after reinstall, but the icons still deactivated and no call (Audio or video) is possible.

it work fine in Browser

**Comment by Ivansss** [comment]
We identified the problem when using Nextcloud Talk 12. We are going to release Talk iOS 13.1.1 today which will include the bugfix for this issue. Sorry for the inconvenince.

**Comment by vmanager** [comment]
I observe the same problem since update to 13.1.0: neither outgoing video or audio works in the iOS app. Incoming video and audio work (for example, from the android client). 

The software versions are the same as for the original reporter above. iOS device was iPhone 8 (iOS version is however the same). The partner call was made with an android device (Android 9, Nextcloud Talk version 13.0.0).

Note that it is possible though to record and send offline audio messages in the app chat but only when microphone is enabled in iOS settings for Nextcloud Talk app. That proves that the problem is in the app and not in the iOS settings.

Please, prioritize, as the iOS client is basically useless except chat.

**Comment by Ivansss** [comment]
Nextcloud Talk iOS version 13.1.1 is already in the App Store
