### ISSUE TITLE
no mic/audio from iOS app running on M1 Mac

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/spreed-ios#729]
Hi, I just tried to have a call with @jospoortvliet and we were able to see each other but he couldn't hear my mic and I couldn't hear his.

He was using talk on iOS and I used the iOS app on my M1 MBP.

**Comment by SystemKeeper** [comment]
Hey @MariusQuabeck 
I looked into this and this is reproducible. The problem is that on iPhones/iPads we're using (have to use) CallKit for call management. So sound input/output is also retrieved through CallKit. Problem is, that all the CallKit classes are available when running talk-ios on a Mac, but they have no functionality, so basically no sound for calls..

At first I thought this might resolve with MacOS Ventura, because CallKit was officially announced for MacOS 13. I tested the current release candidate for MacOS 13 and sadly it doesn't change anything in this regard. So I'll disable CallKit for now when running on a Mac and we'll see if apple at some point fixes this. With disabled CallKit I was able to successfully have calls on Mac.
