### ISSUE TITLE
Unable to connect with iPadOS 16.1 Beta (Error: Unsupported Talk version)

### ISSUE THREAD

**Issue by jacotec** [nextcloud/spreed-ios#908]
## Steps to reproduce
1. Install Talk on an iPad with iPadOS 16.1 Beta
2. Connect to the server
3. Error message "Version Nextcloud Talk not supported" although the server runs the latest version of Talk (14.0.5)

### Expected behaviour
The app should connect to the server

### Actual behaviour
Connecting to the server is refused, stating NC Talk should be updated on the server (which runs the latest version!)

![image](https://user-images.githubusercontent.com/3321655/194266252-2efbd7fe-bceb-47f9-ab60-7576a9bd2dbc.png)

## Device information

**Device:** iPad 2017

**iOS version:** 16.1 Beta (20B5056e)

**Talk version:** 14.0.3

## Server information

**Nextcloud version:** 24.0.4

**Talk version:** 14.0.5

**Custom Signaling server configured:** yes (Version 1.0, 33dc5a554b496bd253bedbecc6755de514a64867)

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

### Server log (data/nextcloud.log)
<details>

```
No relevant server log entries
```
</details>

**Comment by SystemKeeper** [comment]
Hey @jacotec, I tried to reproduce this on simulator, but there everything works fine: 
<img width="378" alt="Bildschirmfoto 2022-10-06 um 15 36 55" src="https://user-images.githubusercontent.com/1580193/194328206-2a5a8af5-b33b-42d0-9ac5-06b2344628cc.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/1580193/194328543-74940034-0acf-49b6-9d6a-011960ee75d3.png">

The error in your screenshot only happens if there were capabilities of talk received, but the minimum capability was not found (minimum is currently 4.0, so that shouldn't be a problem). At this point I'm not sure why you get this message.
Do you have another instance you can test with 16.1 or is this the only one?

**Comment by jacotec** [comment]
Stupid error from my side ... the user was not in a group which is allowed to use Talk :-|

However, the error message could be more clean to express this issue.
